### PR TITLE
Rss feed

### PR DESCRIPTION
**Pull request by Emmanuel-Develops**

### CODE REVIEW

**Comment by Emmanuel-Develops** [comment]
closes #45

**Comment by Emmanuel-Develops** [comment]
RSS Feed is created using summaries from the last 3 months

Feed is located at `/rss.xml` from base route

**Comment by Extheoisah** [comment]
I'm unsure if we want to put the feed link icon at the bottom of the page. How about we put it in the nav header?
what do you think @adamjonas?

**Comment by adamjonas** [comment]
image it certainly doesn't look great on mobile. 

We are going to have to introduce a menu. Let's make it the first nav bar item. Just the icon will suffice.

**Comment by adamjonas** [comment]
Does this make me a designer?

Screen Shot 2023-11-14 at 8 44 24 PM

**Comment by Extheoisah** [comment]
I'm fine with this. @Emmanuel-Develops ??

**Comment by Emmanuel-Develops** [comment]
> I'm fine with this. Atleast till we get the menu design. @Emmanuel-Develops ??

yeah should work

**Review by Extheoisah — APPROVED** [review]

**Pull request merged**
