### PR TITLE
Redesign/home page

### PR DESCRIPTION
**Pull request by IgboPharaoh**
This PR introduces;
- Redesign of the home page 
- Redesign of the component styles
- Structure data fetching from the most recent folder

### CODE REVIEW

**Comment by IgboPharaoh** [comment]
@Extheoisah

**Comment by adamjonas** [comment]
Screenshot 2023-09-27 at 1 18 35 PM

- this should be the full header, not just the first sentence.

Screenshot 2023-09-27 at 1 15 20 PM

- We need a gap between the active and the all activity.

Screenshot 2023-09-27 at 1 15 10 PM
Screenshot 2023-09-27 at 1 47 16 PM

- restore shading and colors for the filters

Screenshot 2023-09-27 at 1 14 55 PM

- The footer should go the full width of the page.

Screenshot 2023-09-27 at 1 14 41 PM

- The orange on the author link appears to be a link, remove styling.
- Restore the coloring of the icons
- For the All Activity, the body should be the first two sentences in sentence form, not in bulletpoint form

**Comment by IgboPharaoh** [comment]
I'll attend to the corrections

**Comment by Emmanuel-Develops** [comment]
Looks good!
I noticed the header has an higher stacking context relative to modal. (The header may not need a stacking index as it has a sticky positioning)
Screenshot 2023-09-29 at 1 14 50 PM

**Comment by adamjonas** [comment]
regression: timeline on combined summaries go behind the header

Screenshot 2023-09-29 at 11 17 13 AM

**Comment by Extheoisah** [comment]
Header regression on mobile
Screenshot_20230929_174713_Samsung Internet

**Review by Extheoisah — APPROVED** [review]

**Pull request merged**
